# This workflow will build and push a node.js application to an Azure Web App when a commit is pushed to your default branch.
#
# This workflow assumes you have already created the target Azure App Service web app.
# For instructions see https://docs.microsoft.com/en-us/azure/app-service/quickstart-nodejs?tabs=linux&pivots=development-environment-cli
#
# To configure this workflow:
#
# 1. Download the Publish Profile for your Azure Web App. You can download this file from the Overview page of your Web App in the Azure Portal.
#    For more information: https://docs.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=applevel#generate-deployment-credentials
#
# 2. Create a secret in your repository named AZURE_WEBAPP_PUBLISH_PROFILE, paste the publish profile contents as the value of the secret.
#    For instructions on obtaining the publish profile see: https://docs.microsoft.com/azure/app-service/deploy-github-actions#configure-the-github-secret
#
# 3. Change the value for the AZURE_WEBAPP_NAME. Optionally, change the AZURE_WEBAPP_PACKAGE_PATH and NODE_VERSION environment variables below.
#
# For more information on GitHub Actions for Azure: https://github.com/Azure/Actions
# For more information on the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# For more samples to get started with GitHub Action workflows to deploy to Azure: https://github.com/Azure/actions-workflow-samples

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: your-app-name    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '14.x'                # set this to the node version to use

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: node-app
        path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: node-app

    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp 
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
void UnlockEverything() {

auto pLootBase = base + 0x9F0C910;// signature 48 8D 0D ? ? ? ? 48 8D 44 24 ? C7 44 (LEA rcx, pLootBase)

struct LootItem {
	int m_itemId;
	int m_itemQuantity;
};

struct StringTable {
	char* name;
	int columnCount;
	int rowCount;
};

auto pInventory = (LootItem*)((uintptr_t)pLootBase + 64);

auto pNumItems = (uint32_t*)((uintptr_t)pLootBase + 240064);

int curCount = *pNumItems;

auto updateOrAddItem = [&] (int itemId, int quantity) {

	bool bFound = false;

	for (int i = 0; i < 30000; i++) {
		if (pInventory[i].itemId == itemId && pInventory[i].quantity < 1) {
			pInventory[i].quantity++;
			bFound = true;
			break;
		}
	}

	if (!bFound) {
		pInventory[curCount].itemId = itemId;
		pInventory[curCount].quantity = 1;

		curCount++;
		(*pNumItems)++;

		*(BYTE*)((uintptr_t)pLootBase + 240072) = 0;
	}
};

StringTable* loot_master = nullptr;

StringTable_GetAsset("loot/loot_master.csv", &loot_master);

for (int i = 1; i < loot_master->rowCount; i++) {

	char* loot_type = StringTable_GetColumnValueForRow(loot_master, i, 2);

	if (strstr(loot_type, "iw8_") || loot_type[0] == '#')
		continue;
		
	char buf[1024];
	
	sprintf_s(buf, "loot/%s_ids.csv", loot_type);

	StringTable * string_table = nullptr;

	StringTable_GetAsset(buf, &string_table);

	if (!string_table)
		continue;

	for (int s = 0; s < string_table->rowCount; s++) {

		updateOrAddItem(atoi(StringTable_GetColumnValueForRow(string_table, s, 0)), 1);
	}
}
}

using MoveResponseToInventory_t = bool(__fastcall*)(LPVOID, int);

MoveResponseToInventory_t fpMoveResponseOrig;

pMoveResponseToInventory = 

bool __fastcall MoveResponseToInventory_Hooked(LPVOID a1, int a2) {

fpMoveResponseOrig(a1, a2);

UnlockEverything();TRUE

MH_RemoveHook(pMoveResponseToInventory);

return false;
}

void SetupYourHook() {
if (MH_CreateHook(pMoveResponseToInventory, MoveResponseToInventory_Hooked, &fpMoveResponseOrig) != MH_SUCCESS) {

	printf("Failed to hook...");
}}


Addresses (latest update):

pMoveResponseToInventory: base + 0x576BB60 // signature 40 53 55 56 57 41 55 41 56 48 83 EC 28 4C

pLootBase: base + 0xA0DC290 // signature 48 8D 0D ? ? ? ? 48 8D 44 24 ? C7 44

StringTable_GetAsset: base + 0x2F56A70 // signature E8 ? ? ? ? 48 8D 15 ? ? ? ? 8D 4B 36

StringTable_GetColumnValueForRow: base + 0x2F56AB0 // signature E8 ? ? ? ? 33 D2 48 8B C8 44 8D 42 16
